# Generated by Django 6.0 on 2026-01-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_consumer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('AUTHORIZED', 'Authorized'), ('DROPPED_OFF', 'Dropped Off'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=20)),
                ('authorization_code', models.CharField(max_length=50, unique=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='returns.consumer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='returns.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_reason', models.CharField(choices=[('DEFECTIVE', 'Defective'), ('WRONG_ITEM', 'Wrong Item'), ('NOT_AS_DESCRIBED', 'Not As Described'), ('UNWANTED', 'Unwanted'), ('OTHER', 'Other')], max_length=20)),
                ('condition', models.CharField(blank=True, choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('DAMAGED', 'Damaged')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['merchant', 'status'], name='returns_ret_merchan_1253c6_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['authorization_code'], name='returns_ret_authori_8b51a5_idx'),
        ),
    ]
