# Generated by Django 6.0.1 on 2026-02-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_return_returnitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnBarLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('partner_type', models.CharField(choices=[('STAPLES', 'Staples'), ('PAPER_SOURCE', 'Paper Source'), ('FEDEX_OFFICE', 'FedEx Office'), ('UPS_STORE', 'UPS Store')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hours_of_operation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city', 'state', 'is_active'], name='returns_ret_city_e03ccc_idx'), models.Index(fields=['zip_code'], name='returns_ret_zip_cod_f98bf3_idx')],
            },
        ),
    ]
