# Generated by Django 6.0.1 on 2026-02-17 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0004_returnbarlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='dropped_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='expected_refund_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='return_bar_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='returns.returnbarlocation'),
        ),
    ]
