# Generated by Django 6.0.1 on 2026-02-18 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0005_return_dropped_off_at_return_expected_refund_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('carrier', models.CharField(choices=[('UPS', 'UPS'), ('FEDEX', 'FedEx'), ('USPS', 'USPS'), ('DHL', 'DHL')], max_length=10)),
                ('label_url', models.URLField(blank=True, max_length=500)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('return_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='returns.return')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
