# Generated by Django 6.0.1 on 2026-02-18 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0006_returnlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemConditionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessed_by', models.CharField(choices=[('RETURN_BAR', 'Return Bar Staff'), ('MERCHANT_WAREHOUSE', 'Merchant Warehouse'), ('AUTOMATED', 'Automated System')], max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('UNSELLABLE', 'Unsellable')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessor_name', models.CharField(blank=True, max_length=100)),
                ('return_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='returns.returnitem')),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
    ]
