# Generated by Django 6.0.1 on 2026-02-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0007_itemconditionassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_method', models.CharField(choices=[('ORIGINAL_PAYMENT', 'Original Payment Method'), ('STORE_CREDIT', 'Store Credit'), ('CHECK', 'Check'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_transactions', to='returns.return')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
    ]
